### ISSUE TITLE
[Trivial] Need verbose option?

### ISSUE THREAD

**Issue by hiroyuki-sato** [bvanassche/ib_srp-backport#1]
Hello Bart.

from README 

    2. Verify that the RESET task management function is processed properly.
       # sg_reset -d ${srp_ini_dev}
      sg_reset: starting device reset
      sg_reset: completed device reset

I tried sg_reset command like the folloing. 
There are not output.

    # sg_reset -d  /dev/sdc
    #

I needed -v options. 

    sg_reset -v -d  /dev/sdc
    sg_reset: starting device reset
    sg_reset: completed device (or target or bus or host) reset

   
* CentOS7
* sg3_utlis: 1.37

--
Hiroyuki Sato.

**Comment by bvanassche** [comment]
Good point, that option has been added in the README. Sorry for the late reaction - it is just a few minutes ago that I noticed this feedback.
