### ISSUE TITLE
dkms build broblem with multiple installed kernels

### ISSUE THREAD

**Issue by Alukardd** [bvanassche/ib_srp-backport#3]
Hello.

I created debian package with dkms module from this source. And when I installed my package dkms build module for all installed kernels. As result I get ib_srp.ko module in each `/lib/modules/<KVER>/updates/dkms/` folders, BUT all of them built for CURRENT kernel.

I solved my problem with ugly patch, but it works for me (got it from scst Makefile):

``` make
diff --git a/Makefile b/Makefile
index 107bf80..535b0a6 100644
--- a/Makefile
+++ b/Makefile
@@ -1,17 +1,8 @@
 #
 # Makefile for scsi_transport_srp.ko and ib_srp.ko.
 #
-
-ifeq ($(KVER),)
-  ifeq ($(KDIR),)
-    KVER = $(shell uname -r)
-    KDIR ?= /lib/modules/$(KVER)/build
-  else
-    KVER = $$KERNELRELEASE
-  endif
-else
-  KDIR ?= /lib/modules/$(KVER)/build
-endif
+export KVER=$(KERNELRELEASE)
+export KDIR=/lib/modules/$(KERNELRELEASE)/build

 VERSION := $(shell sed -n 's/Version:[[:blank:]]*//p' ib_srp-backport.spec)

```

**Comment by bvanassche** [comment]
That's weird. Can you check whether ${KVER} was set? If further work is required on this issue, please reopen this ticket.
